version: "3"
services:
  api_gateway:
    image: nginx
    environment:
      - network="host"
    ports:
      - 443:443
    volumes:
      - ./services/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      main:
        ipv4_address: 172.21.0.10
  user_balancer:
    image: nginx
    environment:
      - network="host"
    expose:
      - 8080
    volumes:
      - ./services/users/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      main:
        ipv4_address: 172.21.0.8
  user:
    build: ./services/users
    networks:
      main:
  user_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5430:5432
    volumes:
      - db:/var/lib/postgresql/data

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  db:
    driver: local
