apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend
  labels:
    app:  frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  frontend
    spec:
      containers:
      - image: frontend
        name:  frontend
        resources:
          requests:
            cpu: "20m"
            memory: "200M"                 
        imagePullPolicy: Never
        ports:
        - containerPort:  80
          name:  frontend       
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service  
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port:  8080
    targetPort: 80
    nodePort: 30003