apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  containers:
    - image: rabbitmq:3-management-alpine
      name:  rabbitmq      
      imagePullPolicy: IfNotPresent
      env:
        - name:  RABBITMQ_DEFAULT_USER
          value:  admin
        - name: RABBITMQ_DEFAULT_PASS
          value: admin      
      ports:                                          
      - containerPort:  15672          
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-con
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:  
    - port: 5672
      targetPort: 5672                      
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-web
spec:
  type: NodePort
  ports:  
    - port: 15672
      targetPort: 15672    
      nodePort: 30001
  selector:
    app: rabbitmq
  
      