apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  containers:
    - image: rabbitmq:3-management-alpine
      name:  rabbitmq      
      imagePullPolicy: IfNotPresent
      env:
        - name:  RABBITMQ_DEFAULT_USER
          value:  admin
        - name: RABBITMQ_DEFAULT_PASS
          value: admin      
      ports:
      - containerPort:  15672              
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  ports:  
    - port: 15672
      targetPort: 15672
      nodePort: 30001      
  selector:
    app: rabbitmq
      