apiVersion: v1
kind: Pod
metadata:
  name: users
  labels:
    app: users
spec:
  containers:
    - image: users      
      name: users
      imagePullPolicy: Never
      ports:
        - containerPort: 3535
---
apiVersion: v1
kind: Service
metadata:
  name: users-service  
spec:
  type: NodePort
  selector:
    app: users
  ports:
  - port:  8080
    targetPort: 3535
    nodePort: 30002
    