apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      name: users
      labels:
        app: users
    spec:
      containers:
        - image: users      
          name: users
          resources:
          requests:
            cpu: "10m"
            memory: "300M"   
          imagePullPolicy: Never
          ports:
            - containerPort: 3535
---
apiVersion: v1
kind: Service
metadata:
  name: users-service  
spec:
  type: NodePort
  selector:
    app: users
  ports:
  - port:  8080
    targetPort: 3535
    nodePort: 30002
    