apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      name: users
      labels:
        app: users
    spec:
      containers:
        - image: users      
          name: users
          resources:
            limits:
              cpu: "50m"
              memory: "300M"   
          imagePullPolicy: Never
          ports:
            - containerPort: 3535
---
apiVersion: v1
kind: Service
metadata:
  name: users-service  
spec:
  type: NodePort
  selector:
    app: users
  ports:
  - port:  8080
    targetPort: 3535
    nodePort: 30002
---
apiVersion: v1
kind: Pod
metadata:
  name: usersdb
  labels:
    app: usersdb
spec:
  containers:
  - name: usersdb
    image: postgres    
    # resources:
    #   limits:
    #     memory: "514Mi"
    #     cpu: "300m"
    ports:
      - containerPort: 5432 
    env:
    - name:  POSTGRES_PASSWORD
      value: admin 
---
apiVersion: v1
kind: Service
metadata:
  name: usersdb-service  
spec:  
  selector:
    app: usersdb
  ports:
  - port:  5432
    targetPort: 5432    
---
apiVersion: v1
kind: Pod
metadata:
  name: usersdb-admin
  labels:
    app: usersdb-admin
spec:
  containers:
  - name: usersdb-admin
    image: dpage/pgadmin4    
    # resources:
    #   limits:
    #     memory: "514Mi"
    #     cpu: "300m"
    ports:
      - containerPort: 80 
    env:
    - name:  PGADMIN_DEFAULT_PASSWORD
      value: admin 
    - name:  PGADMIN_DEFAULT_EMAIL
      value: admin@admin.local
---
apiVersion: v1
kind: Service
metadata:
  name: usersdb-admin-service  
spec:  
  type: NodePort
  selector:
    app: usersdb
  ports:
  - port:  80
    targetPort: 80
    nodePort: 30004